devbox:
  build: devbox
  hostname: devbox
  ports:
    - "2222:22"
    - "8000-8001:8000-8001"
    - "8100:8100"
    - "3019:3019" # frontend prototypes
    - "3000-3001:3000-3001" # frontend prototypes
    - "35729:35729"
  volumes:
    - ..:/data

samba:
  build: samba
  volumes:
    - "..:/data"
  ports:
    - "137-139:137-139"
    - "445:445"
